[mcp_servers.spec-workflow]
args = [
    "--no-install",
    "spec-workflow-mcp",
    ".",
]
command = "npx"

[mcp_servers.supabase]
args = [
    "-y",
    "@supabase/mcp-server-supabase",
    "--project-ref",
    "mlcptrkvkseyqxxlfcme",
]
command = "npx"
env_vars = ["SUPABASE_ACCESS_TOKEN"]

[mcp_servers.serena]
startup_timeout_sec = 60
args = [
    "-p",
    "3.13",
    "--from",
    "serena-agent",
    "serena",
    "start-mcp-server",
    "--project",
    "E:/code/jjg-admin-react-github",
    "--context=codex",
]
command = "C:/Users/Administrator/.local/bin/uvx.exe"

[mcp_servers.context7]
args = [
    "-y",
    "@upstash/context7-mcp@latest",
]
command = "npx"

[mcp_servers.chrome-devtools]
args = [
    "-y",
    "chrome-devtools-mcp@latest",
]
command = "npx"
