export interface PagePermissionRoute {
  path: string
  permission: string
}

export const PAGE_PERMISSION_ROUTES: PagePermissionRoute[] = [
  { path: '/dashboard', permission: 'page:dashboard' },
  { path: '/syney-spec-list', permission: 'page:syney-spec-list' },
  { path: '/syney-store-report-list', permission: 'page:syney-store-report-list' },
  { path: '/syney-po-list', permission: 'page:syney-po-list' },
  { path: '/syney-safe-part-setting', permission: 'page:syney-safe-part-setting' },
  { path: '/syney-setting', permission: 'page:syney-setting' },
  { path: '/workshop-order-list', permission: 'page:workshop-order-production' },
  { path: '/production-scheduling', permission: 'page:production-scheduling' },
  { path: '/order-scheduling', permission: 'page:order-scheduling' },
  { path: '/employee-list', permission: 'page:employee-list' },
  { path: '/employee/change-password', permission: 'page:mobile-change-password' },
  { path: '/standard-time-list', permission: 'page:standard-time-list' },
  { path: '/job-base-setting', permission: 'page:job-base-setting' },
  { path: '/machine-equipment-maintenance', permission: 'page:machine-equipment-maintenance' },
  { path: '/material-transfer', permission: 'page:material-transfer' },
  { path: '/material-transfer/scan', permission: 'page:mobile-scan-material-transfer' },
  { path: '/precision-finishing-cutting', permission: 'page:precision-finishing-cutting' },
  { path: '/precision-finishing-cutting/scan', permission: 'page:mobile-scan-precision-finishing' },
  { path: '/scan', permission: 'page:mobile-scan-hub' },
  { path: '/production-order', permission: 'page:production-order' },
  { path: '/production-order/create', permission: 'page:mobile-production-order' },
  { path: '/production-order/scan', permission: 'page:mobile-scan-production-order' },
  { path: '/production-daily-report', permission: 'page:production-daily-report' },
  { path: '/quality-rework-repair', permission: 'page:quality-rework-repair' },
  { path: '/quality-issue-record', permission: 'page:quality-issue-record' },
  { path: '/machine-runtime', permission: 'page:machine-runtime' },
  { path: '/precision-cutting-transfer', permission: 'page:precision-cutting-transfer' },
  { path: '/tooling-data', permission: 'page:tooling-data' },
  { path: '/tooling-inventory', permission: 'page:tooling-inventory' },
  { path: '/tooling-stock-in', permission: 'page:tooling-stock-in' },
  { path: '/tooling-stock-out', permission: 'page:tooling-stock-out' },
  { path: '/labor-protection-data', permission: 'page:labor-protection-data' },
  { path: '/labor-protection-requisition', permission: 'page:labor-protection-requisition' },
  { path: '/youmai-product-data', permission: 'page:youmai-product-data' },
  { path: '/youmai-finished-goods-inventory', permission: 'page:youmai-finished-goods-inventory' },
  { path: '/youmai-finished-goods-stock-in', permission: 'page:youmai-finished-goods-stock-in' },
  { path: '/youmai-finished-goods-stock-out', permission: 'page:youmai-finished-goods-stock-out' },
  { path: '/youmai-raw-material-inventory', permission: 'page:youmai-raw-material-inventory' },
  { path: '/youmai-raw-material-stock-in', permission: 'page:youmai-raw-material-stock-in' },
  { path: '/youmai-raw-material-stock-out', permission: 'page:youmai-raw-material-stock-out' },
  { path: '/attendance-detail', permission: 'page:attendance-detail' },
  { path: '/attendance-summary', permission: 'page:attendance-summary' },
  { path: '/access-management', permission: 'page:access-management' },
  { path: '/villa-lift-order-list', permission: 'page:villa-lift-order-list' },
  { path: '/villa-lift-cutting-process', permission: 'page:villa-lift-cutting-process' },
  { path: '/villa-lift-processing', permission: 'page:villa-lift-processing' },
  { path: '/packaging-process-employee-list', permission: 'page:packaging-process-employee-list' },
  { path: '/packaging-process-standard-time-list', permission: 'page:packaging-process-standard-time-list' },
  { path: '/packaging-process-work-order-list', permission: 'page:packaging-process-work-order-list' },
  { path: '/extrusion-production-order', permission: 'page:extrusion-production' },
  { path: '/extrusion-production-daily-report', permission: 'page:extrusion-production-daily-report' },
]
