import type { PermissionDefinition } from '@/types/permission'

export const VILLA_LIFT_PERMISSIONS: PermissionDefinition[] = [
  // 导航
  {
    key: 'nav:villa-lift',
    scope: 'nav',
    module: 'villa-lift',
    surface: 'pc',
    label: '别墅梯菜单分组',
  },

  // 页面
  {
    key: 'page:villa-lift-order-list',
    scope: 'page',
    module: 'villa-lift',
    surface: 'pc',
    label: '别墅梯订单管理',
  },
  {
    key: 'page:villa-lift-cutting-process',
    scope: 'page',
    module: 'villa-lift',
    surface: 'pc',
    label: '别墅梯切割工序',
  },
  {
    key: 'page:villa-lift-processing',
    scope: 'page',
    module: 'villa-lift',
    surface: 'pc',
    label: '别墅梯加工工序',
  },

  // ── 订单管理按钮级权限 ──────────────────────────────
  {
    key: 'feature:villa-lift-order.create',
    scope: 'feature',
    module: 'villa-lift',
    surface: 'pc',
    label: '别墅梯订单-新建',
    description: '控制「新建订单」按钮的可见性',
  },
  {
    key: 'feature:villa-lift-order.edit',
    scope: 'feature',
    module: 'villa-lift',
    surface: 'pc',
    label: '别墅梯订单-编辑',
    description: '控制订单行内「编辑」按钮的可见性',
  },
  {
    key: 'feature:villa-lift-order.edit-items',
    scope: 'feature',
    module: 'villa-lift',
    surface: 'pc',
    label: '别墅梯订单-编辑明细',
    description: '控制展开行中「编辑明细」按钮的可见性',
  },
  {
    key: 'feature:villa-lift-order.delete',
    scope: 'feature',
    module: 'villa-lift',
    surface: 'pc',
    label: '别墅梯订单-批量删除',
    description: '控制「批量删除」按钮的可见性',
  },
  {
    key: 'feature:villa-lift-order.close',
    scope: 'feature',
    module: 'villa-lift',
    surface: 'pc',
    label: '别墅梯订单-批量结案',
    description: '控制「批量结案」按钮的可见性',
  },
  {
    key: 'feature:villa-lift-order.reopen',
    scope: 'feature',
    module: 'villa-lift',
    surface: 'pc',
    label: '别墅梯订单-批量反结案',
    description: '控制「批量反结案」按钮的可见性',
  },
  {
    key: 'feature:villa-lift-order.mark-material',
    scope: 'feature',
    module: 'villa-lift',
    surface: 'pc',
    label: '别墅梯订单-挑料完成',
    description: '控制「挑料完成」按钮的可见性',
  },
  {
    key: 'feature:villa-lift-order.mark-painting',
    scope: 'feature',
    module: 'villa-lift',
    surface: 'pc',
    label: '别墅梯订单-喷涂完成',
    description: '控制「喷涂完成」按钮的可见性',
  },
  {
    key: 'feature:villa-lift-order.mark-film',
    scope: 'feature',
    module: 'villa-lift',
    surface: 'pc',
    label: '别墅梯订单-贴膜完成',
    description: '控制「贴膜完成」按钮的可见性',
  },
  {
    key: 'feature:villa-lift-order.mark-cutting',
    scope: 'feature',
    module: 'villa-lift',
    surface: 'pc',
    label: '别墅梯订单-切割完成',
    description: '控制「切割完成」按钮的可见性',
  },
  {
    key: 'feature:villa-lift-order.mark-processing',
    scope: 'feature',
    module: 'villa-lift',
    surface: 'pc',
    label: '别墅梯订单-加工完成',
    description: '控制「加工完成」按钮的可见性',
  },
  {
    key: 'feature:villa-lift-order.mark-cabin-processing',
    scope: 'feature',
    module: 'villa-lift',
    surface: 'pc',
    label: '别墅梯订单-轿箱加工完成',
    description: '控制「轿箱加工完成」按钮的可见性',
  },
  {
    key: 'feature:villa-lift-order.mark-middle-door-processing',
    scope: 'feature',
    module: 'villa-lift',
    surface: 'pc',
    label: '别墅梯订单-中分门加工完成',
    description: '控制「中分门加工完成」按钮的可见性',
  },
  {
    key: 'feature:villa-lift-order.mark-frame-processing',
    scope: 'feature',
    module: 'villa-lift',
    surface: 'pc',
    label: '别墅梯订单-井架加工完成',
    description: '控制「井架加工完成」按钮的可见性',
  },

  // ── 切割工序按钮级权限 ──────────────────────────────
  {
    key: 'feature:villa-lift-cutting.create',
    scope: 'feature',
    module: 'villa-lift',
    surface: 'pc',
    label: '别墅梯切割-新建',
    description: '控制「新建切割记录」按钮的可见性',
  },
  {
    key: 'feature:villa-lift-cutting.edit',
    scope: 'feature',
    module: 'villa-lift',
    surface: 'pc',
    label: '别墅梯切割-编辑',
    description: '控制切割记录行内「编辑」按钮的可见性',
  },
  {
    key: 'feature:villa-lift-cutting.delete',
    scope: 'feature',
    module: 'villa-lift',
    surface: 'pc',
    label: '别墅梯切割-批量删除',
    description: '控制切割记录「批量删除」按钮的可见性',
  },

  // ── 加工工序按钮级权限 ──────────────────────────────
  {
    key: 'feature:villa-lift-finishing.create',
    scope: 'feature',
    module: 'villa-lift',
    surface: 'pc',
    label: '别墅梯加工-新建',
    description: '控制「新建加工记录」按钮的可见性',
  },
  {
    key: 'feature:villa-lift-finishing.edit',
    scope: 'feature',
    module: 'villa-lift',
    surface: 'pc',
    label: '别墅梯加工-编辑',
    description: '控制加工记录行内「编辑」按钮的可见性',
  },
  {
    key: 'feature:villa-lift-finishing.delete',
    scope: 'feature',
    module: 'villa-lift',
    surface: 'pc',
    label: '别墅梯加工-批量删除',
    description: '控制加工记录「批量删除」按钮的可见性',
  },
]
